version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      target: prod
    image: rfid_lab:${RFID_LAB_VERSION:-latest}
    restart: always
    env_file:
    - .env
    environment:
      RFID_LAB_HOST: 0.0.0.0
      RFID_LAB_DB_FILE: /db_data/db.sqlite3
    volumes:
    - rfid_lab-db-data:/db_data/

  migrator:
    image: rfid_lab:${RFID_LAB_VERSION:-latest}
    restart: "no"
    command: aerich upgrade
    environment:
      RFID_LAB_DB_FILE: /db_data/db.sqlite3
    volumes:
    - rfid_lab-db-data:/db_data/



volumes:
  rfid_lab-db-data:
    name: rfid_lab-db-data
